<?php

use Illuminate\Support\Carbon;

return [

    'positionNames' => [
        'Nhân viên phân tích dữ liệu',
        'Quản trị hệ thống',
        'Lập trình viên',
        'Kỹ sư phần mềm',
        'Nhân viên phân tích hệ thống',
        'Chuyên viên hỗ trợ kỹ thuật/ người sử dụng cuối cùng',
        'Thiết kế web/ dịch vụ Internet',
        'Người giám sát',
        'Trưởng Nhóm',
        'Sếp',
        'trợ lí giám đốc',
        'thư kí',
        'nhân viên',
        'Cán bộ, viên chức',
        'tổng giám đốc',
        'quản lý',
        'giám đốc',
        'phó giám đốc',
        'Hội đồng quản trị',
        'trưởng phòng',
        'phó trưởng phòng',
        'thư kí',
        'nhân viên',
        'Giám đốc',
        'Phó Giám đốc',
        'giám đốc điều hành',
        'giám đốc thông tin',
        'trưởng phòng hoạt động',
        'giám đốc tài chính',
        'phó chủ tịch',
        'Quản lý',
        'trưởng phòng',
        'Trưởng Bộ phận',
        'trưởng phòng nhân sự',
        'trưởng phòng tài chính',
        'trưởng phòng kế toán',
        'trưởng phòng sản xuất',
        'trưởng phòng marketing',
        'Trưởng Nhóm',
        'Sếp',
        'trợ lí giám đốc',
        'thư kí',
        'nhân viên',
        'Giám đốc',
        'Giám đốc điều hành',
        'Giám đốc thông tin',
        'Giám đốc tài chính',
        'Chủ tịch',
        'Trưởng phòng hoạt động',
        'Thành viên ban quản trị',
        'Phó Giám đốc',
        'Phó chủ tịch',
        'Quản lý',
        'trưởng phòng nhân sự',
        'trưởng phòng tài chính',
        'trưởng phòng kế toán',
        'trưởng phòng sản xuất',
        'trưởng phòng marketing',
        'Người giám sát',
        'Trưởng Nhóm',
        'trợ lí giám đốc',
        'Trưởng Bộ phận',
        'trưởng phòng',
        'người giám sát',
        'Thư kín',
        'nhân viên',
        'Giám đốc',
        'Phó Giám đốc',
        'giám đốc điều hành',
        'giám đốc thông tin',
        'trưởng phòng hoạt động',
        'giám đốc tài chính',
        'Chủ tịch',
        'phó chủ tịch',
        'Quản lý',
        'trưởng phòng',
        'Trưởng Bộ phận',
        'trưởng phòng nhân sự',
        'trưởng phòng tài chính',
        'trưởng phòng kế toán',
        'trưởng phòng sản xuất',
        'trưởng phòng marketing',
        'Người giám sát',
        'Trưởng Nhóm',
        'Sếp',
        'trợ lí giám đốc',
        'thư kí',
        'nhân viên',
        'Phó phòng kinh doanh',
    ],

    'regions' => [
        ['name' => 'Tây Bắc Bộ', 'created_at' => Carbon::now()],
        ['name' => 'Đông Bắc bộ', 'created_at' => Carbon::now()],
        ['name' => 'Đồng bằng sông Hồng', 'created_at' => Carbon::now()],
        ['name' => 'Bắc Trung Bộ', 'created_at' => Carbon::now()],
        ['name' => 'Nam Trung Bộ', 'created_at' => Carbon::now()],
        ['name' => 'Tây Nguyên', 'created_at' => Carbon::now()],
        ['name' => 'Đông Nam Bộ', 'created_at' => Carbon::now()],
        ['name' => 'Tây Nam Bộ', 'created_at' => Carbon::now()]
    ],

    'fullnames' =>
    [
        'Đương Hoàng Ân',
        'Lý Kiên Bình',
        'Chiêm Hữu Cảnh',
        'Liên Mạnh Dũng',
        'Mạc Tạ Hiền',
        'Lại Trung Hiếu',
        'Phí Ðức Hòa',
        'Ngọc Công Lý',
        'Ngạc Anh Minh',
        'Mục Bình Nguyên',
        'Ao Thanh Phong',
        'Chu Minh Quân',
        'Cổ Vương Triều',
        'Đậu Hoài Trung',
        'Bạch Ðình Tuấn',
        'Ngạc Quang Tuấn',
        'Tào Anh Thái',
        'Phương Quyết Thắng',
        'Hàn Kim Thịnh',
        'Văn Kim Thịnh',
        'Nhan Cao Thọ',
        'Quảng Vạn Thông',
        'Uông Hải Thụy',
        'Chế Vũ Uy',
        'Tinh Thế Vinh',
        'Tinh Nam An',
        'Lạc Thành An',
        'Thái Bảo Châu',
        'Trác Phúc Cường',
        'Hướng Trí Dũng',
        'Hà Minh Khôi',
        'Võ Việt Khôi',
        'Lèng Sơn Hải',
        'Lã Trung Hiếu',
        'Mầu Công Lập',
        'Triệu Thành Nguyên',
        'Tấn Trung Nguyên',
        'Giáp Hồng Phát',
        'Cổ Chấn Phong',
        'Doãn Ðình Phú',
        'Linh Cao Sơn',
        'Diêm Thành Tín',
        'Ấu Quang Trung',
        'Phương Hữu Từ',
        'Vưu Việt Thái',
        'Ánh Vạn Thắng',
        'Ứng Công Thành',
        'Đỗ Huy Thông',
        'Trịnh Minh Thuận',
        'Kiều Gia Uy'
    ]

];
